{
  "uid" : "191bc89f1b0b9812",
  "name" : "TestCheckInit.test_two_arg_in_func",
  "title" : "Test two arg in func",
  "time" : {
    "start" : 1525896491396,
    "stop" : 1525896491415,
    "duration" : 19
  },
  "summary" : {
    "attachments" : 0,
    "steps" : 0
  },
  "failure" : {
    "message" : "TypeError: check_ident() takes exactly 1 argument (2 given)",
    "stackTrace" : "self = <test_first.TestCheckInit instance at 0x7f9220c64a70>\n\n    @allure.story(\"Checking the output with two param\")\n    def test_two_arg_in_func(self):\n>       result = Check.check_ident(\"9876543219 9\",\"9876543219 9\")\nE       TypeError: check_ident() takes exactly 1 argument (2 given)\n\ntest_first.py:36: TypeError"
  },
  "description" : null,
  "severity" : "NORMAL",
  "status" : "FAILED",
  "testId" : null,
  "suite" : {
    "uid" : "2f164933aa0032d9",
    "name" : "test_first",
    "title" : "Test first"
  },
  "steps" : [ ],
  "attachments" : [ ],
  "issues" : [ ],
  "labels" : [ {
    "name" : "story",
    "value" : "Checking the output with two param"
  }, {
    "name" : "suite-name",
    "value" : "test_first"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "suite-title",
    "value" : null
  }, {
    "name" : "host",
    "value" : "familypc"
  }, {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "thread",
    "value" : "4773-MainThread"
  }, {
    "name" : "language",
    "value" : "cpython2"
  } ],
  "parameters" : [ ]
}